name: Test

on:
  push:
    branches: [master]
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install Jupyter
        run: |
          which pip
          which python
          python -c "import sys; print(sys.executable)"
          pip install wheel
          pip install jupyter
      - name: Install Checklist
        run: |    
          pip install --no-build-isolation checklist==0.0.11
      - name: Install package
        run: |
          pip install .[test]
      - name: Run tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          make test